version: "3.9"
services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build: ./app
    expose:
      - "5000"
    depends_on:
      - db

  db:
    build: ./db
    expose:
      - "6000"

  honeypot:
    build: ./honeypot
    ports:
      - "8080:8080"
